name: Test Self-hosted runner GKE

on:
  push:
    branches:
      - develop
      - main
  
  workflow_dispatch:

jobs:
  hola-mundo-gke:
    runs-on: self-hosted

    steps:
      - name: Hello world
        run: echo "hello world"
